INSERT INTO user(ROLE, LOGIN, PASSWORD) VALUES
('ADMIN', 'amaks', SHA1('maks')),
('USER', 'umaks', SHA1('maks')),
('USER', 'uanna', SHA1('maks'));

INSERT INTO conference(NAME, DATE) VALUES
('Conference', '2021-01-11 15:00:00'),
('Web Conference', '2021-03-25 15:00:00'),
('Online Conference', '2021-01-16 15:00:00'),
('WebDev Conference', '2021-04-26 10:00:00'),
('GameDev Conference', '2021-01-26 15:00:00'),
('Financial Conference', '2021-07-21 10:00:00'),
('Legal Conference', '2021-10-15 10:00:00'),
('Engineering Conference', '2021-11-15 10:00:00'),
('Design Conference', '2021-12-17 10:00:00'),
('Flower Conference', '2021-05-19 10:00:00'),
('WebSecurity Conference', '2021-03-21 10:00:00'),
('Developer Conference', '2021-04-20 10:00:00'),
('Auto Conference', '2021-02-02 10:00:00');

INSERT INTO section(CONFERENCE_ID, NAME, STATUS) VALUES
('1', 'Section 1', 'ACTUAL' ),
('1', 'Section 2', 'ACTUAL'),
('1', 'Section 3', 'ACTUAL'),
 ('2', 'Web section 1', 'ACTUAL'),
 ('2', 'Web section 2', 'ACTUAL'),
 ('2', 'Web section 3', 'ACTUAL'),
 ('3', 'Online section 1', 'ACTUAL'),
 ('3', 'Online section 2', 'ACTUAL'),
 ('3', 'Online section 3', 'ACTUAL'),
 ('4', 'WebDev section 1', 'ACTUAL'),
 ('4', 'WebDev section 2', 'ACTUAL'),
 ('4', 'WebDev section 3', 'ACTUAL'),
 ('5', 'GameDev section 1', 'ACTUAL'),
 ('5', 'GameDev section 2', 'ACTUAL'),
 ('5', 'GameDev section 3', 'ACTUAL'),
 ('6', 'Financial section 1', 'ACTUAL'),
 ('6', 'Financial section 2', 'ACTUAL'),
 ('6', 'Financial section 3', 'ACTUAL'),
 ('7', 'Legal section 1', 'ACTUAL'),
 ('7', 'Legal section 2', 'ACTUAL'),
 ('7', 'Legal section 3', 'DEPRECATED'),
 ('7', 'Legal section 4','ACTUAL'),
 ('8', 'Engineering section 1', 'ACTUAL'),
 ('8', 'Engineering section 2', 'ACTUAL'),
 ('8', 'Engineering section 3', 'ACTUAL'),
 ('8', 'Engineering section 4', 'DEPRECATED'),
 ('9', 'Design section 1', 'ACTUAL'),
 ('9', 'Design section 2', 'ACTUAL'),
 ('9', 'Design section 3', 'ACTUAL'),
 ('10', 'Flower section 1', 'ACTUAL'),
 ('10', 'Flower section 2', 'ACTUAL'),
 ('10', 'Flower section 3', 'ACTUAL'),
 ('11', 'WebSecurity section 1', 'ACTUAL'),
 ('11', 'WebSecurity section 2', 'ACTUAL'),
 ('11', 'WebSecurity section 3', 'ACTUAL'),
('11', 'WebSecurity section 3', 'ACTUAL'),
 ('12', 'Developer section 1', 'ACTUAL'),
 ('12', 'Developer section 2', 'ACTUAL'),
 ('13', 'Auto section 1', 'ACTUAL'),
 ('13', 'Auto section 2', 'DEPRECATED'),
 ('13', 'Auto section 3', 'ACTUAL'),
 ('13', 'Auto section 4', 'ACTUAL');

INSERT INTO request(USER_ID, SECTION_ID, TOPIC, STATUS) VALUES
('2', '1', 'Conference section topic', 'ACCEPTED'),
('3', '14', 'Game dev section topic', 'ACCEPTED'),
('2', '21', 'Legal section topic', 'CONSIDERING'),
('2', '26', 'Engineering section topic', 'REJECTED'),
('3', '28', 'Design section topic', 'CONSIDERING'),
('2', '34', 'Web security topic', 'CONSIDERING'),
('3', '16', 'Financial section topic', 'CONSIDERING'),
('2', '30', 'Flower section topic', 'DEPRECATED'),
('2', '11', 'WebDev topic', 'CONSIDERING'),
('3', '27', 'Design topic', 'CONSIDERING');

INSERT INTO question(USER_ID, CONFERENCE_ID, CONTENT) VALUES
('2', '11', 'User question about WebSecurity conference?'),
('3', '6', 'User question about Financial conference ?'),
('2', '10', 'User question about Flower conference?'),
('3', '3', 'User question about Online conference?'),
('2', '14', 'User question about Web conference?');