

CREATE SCHEMA IF NOT EXISTS `CONFERENCE` DEFAULT CHARACTER SET utf8 ;
USE `CONFERENCE` ;


CREATE TABLE IF NOT EXISTS `Conference`.`CONFERENCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(150) NOT NULL,
  `DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
  )


CREATE TABLE IF NOT EXISTS `Conference`.`SECTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONFERENCE_ID` INT NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`)
  )



CREATE TABLE IF NOT EXISTS `Conference`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  `LOGIN` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
  )



CREATE TABLE IF NOT EXISTS `Conference`.`TOPIC` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `SECTION_ID` INT NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  `STATUS` ENUM('CONSIDERING', 'REJECTED', 'ACCEPTED') NOT NULL DEFAULT 'CONSIDERING',
  PRIMARY KEY (`ID`)
)



CREATE TABLE IF NOT EXISTS `Conference`.`QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
)



CREATE TABLE IF NOT EXISTS `Conference`.`ANSWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  `QUESTION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
  )
